/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404/': RouteRecordInfo<'/404/', '/404', Record<never, never>, Record<never, never>>,
    '/admin/roles/': RouteRecordInfo<'/admin/roles/', '/admin/roles', Record<never, never>, Record<never, never>>,
    '/admin/system/': RouteRecordInfo<'/admin/system/', '/admin/system', Record<never, never>, Record<never, never>>,
    '/admin/users/': RouteRecordInfo<'/admin/users/', '/admin/users', Record<never, never>, Record<never, never>>,
    '/common/notifications/': RouteRecordInfo<'/common/notifications/', '/common/notifications', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/doctor/emergency/': RouteRecordInfo<'/doctor/emergency/', '/doctor/emergency', Record<never, never>, Record<never, never>>,
    '/doctor/family-patients/': RouteRecordInfo<'/doctor/family-patients/', '/doctor/family-patients', Record<never, never>, Record<never, never>>,
    '/doctor/medical-records/': RouteRecordInfo<'/doctor/medical-records/', '/doctor/medical-records', Record<never, never>, Record<never, never>>,
    '/doctor/patients/': RouteRecordInfo<'/doctor/patients/', '/doctor/patients', Record<never, never>, Record<never, never>>,
    '/error/403': RouteRecordInfo<'/error/403', '/error/403', Record<never, never>, Record<never, never>>,
    '/error/404': RouteRecordInfo<'/error/404', '/error/404', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/patient/medical-history/': RouteRecordInfo<'/patient/medical-history/', '/patient/medical-history', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
    '/research/projects/': RouteRecordInfo<'/research/projects/', '/research/projects', Record<never, never>, Record<never, never>>,
    '/research/projects/AuditStatsView': RouteRecordInfo<'/research/projects/AuditStatsView', '/research/projects/AuditStatsView', Record<never, never>, Record<never, never>>,
    '/research/projects/SelectionView': RouteRecordInfo<'/research/projects/SelectionView', '/research/projects/SelectionView', Record<never, never>, Record<never, never>>,
  }
}
